//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ErpByNetR1100Entities : DbContext
    {
        public ErpByNetR1100Entities()
            : base("name=ErpByNetR1100Entities")
        {
            var adapter = (IObjectContextAdapter)this;
            var objectContext = adapter.ObjectContext;
            objectContext.CommandTimeout = 60 * 60;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fsp_DocumentDetails> fsp_DocumentDetails { get; set; }
        public virtual DbSet<fsp_Documents> fsp_Documents { get; set; }
    
        public virtual ObjectResult<fsp_GetCOABudgetSummary_Result> fsp_GetCOABudgetSummary(string purchaseRequisitionNo)
        {
            var purchaseRequisitionNoParameter = purchaseRequisitionNo != null ?
                new ObjectParameter("PurchaseRequisitionNo", purchaseRequisitionNo) :
                new ObjectParameter("PurchaseRequisitionNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fsp_GetCOABudgetSummary_Result>("fsp_GetCOABudgetSummary", purchaseRequisitionNoParameter);
        }
    
        public virtual ObjectResult<fsp_ReportMiscPurchaseRequisition_Result> fsp_ReportMiscPurchaseRequisition(string purchaseRequisitionNo)
        {
            var purchaseRequisitionNoParameter = purchaseRequisitionNo != null ?
                new ObjectParameter("PurchaseRequisitionNo", purchaseRequisitionNo) :
                new ObjectParameter("PurchaseRequisitionNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fsp_ReportMiscPurchaseRequisition_Result>("fsp_ReportMiscPurchaseRequisition", purchaseRequisitionNoParameter);
        }
    
        public virtual ObjectResult<fsp_ReportSubconPO_CumulativeDetails_Result> fsp_ReportSubconPO_CumulativeDetails(string purchaseOrderNo)
        {
            var purchaseOrderNoParameter = purchaseOrderNo != null ?
                new ObjectParameter("PurchaseOrderNo", purchaseOrderNo) :
                new ObjectParameter("PurchaseOrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fsp_ReportSubconPO_CumulativeDetails_Result>("fsp_ReportSubconPO_CumulativeDetails", purchaseOrderNoParameter);
        }
    
        public virtual ObjectResult<fsp_ReportPurchaseOrder_sg_Result> fsp_ReportPurchaseOrder_sg(string purchaseOrderNo)
        {
            var purchaseOrderNoParameter = purchaseOrderNo != null ?
                new ObjectParameter("PurchaseOrderNo", purchaseOrderNo) :
                new ObjectParameter("PurchaseOrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fsp_ReportPurchaseOrder_sg_Result>("fsp_ReportPurchaseOrder_sg", purchaseOrderNoParameter);
        }
    }
}
