//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DocumentDetails
    {
        public long StatusChangeHistoryID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string ChangedByUser { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string DocType { get; set; }
        public string DocNo { get; set; }
        public Nullable<long> DocNoID { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<long> DocID { get; set; }
        public string Status { get; set; }
        public string AddedbyUser { get; set; }
    }
}
