//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Documents4AlternateApproval
    {
        public long DocID { get; set; }
        public string DocType { get; set; }
        public string DocNo { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public string Currency { get; set; }
        public string SubmitBy { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> ApprovalSubmitDate { get; set; }
        public string ApprovalSubmitBy { get; set; }
        public string Status { get; set; }
        public string AttachDoc { get; set; }
        public string AddAttachDoc1 { get; set; }
        public string AddAttachDoc2 { get; set; }
        public string AddAttachDoc3 { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string VendorCategory { get; set; }
        public string IssueBy { get; set; }
        public Nullable<decimal> DocNetPrice { get; set; }
        public string PRNumbers { get; set; }
        public Nullable<decimal> PRAmount { get; set; }
        public Nullable<short> PriorityCode { get; set; }
        public bool ERPAttachment { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public long WorkFlowID { get; set; }
        public string ApprovePerson { get; set; }
        public string Alternate1 { get; set; }
        public string Alternate2 { get; set; }
        public string WorkFlowStatus { get; set; }
        public Nullable<System.DateTime> WorkFlowSubmitDate { get; set; }
        public Nullable<int> AlternateApprover { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string RejectBy { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public string Approver { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<short> ApprovalLevel { get; set; }
        public string RFQRefNo { get; set; }
        public string LastApprovalSubmitBy { get; set; }
        public Nullable<System.DateTime> LastApprovalSubmitDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
