//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Documents
    {
        public long DocID { get; set; }
        public string DocType { get; set; }
        public string DocNo { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public string Currency { get; set; }
        public string SubmitBy { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> ApprovalSubmitDate { get; set; }
        public string ApprovalSubmitBy { get; set; }
        public string Status { get; set; }
        public string AttachDoc { get; set; }
        public string AddAttachDoc1 { get; set; }
        public string AddAttachDoc2 { get; set; }
        public string AddAttachDoc3 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string VendorCategory { get; set; }
        public string IssueBy { get; set; }
        public Nullable<decimal> DocNetPrice { get; set; }
        public string PRNumbers { get; set; }
        public Nullable<decimal> PRAmount { get; set; }
        public Nullable<short> PriorityCode { get; set; }
        public Nullable<bool> IsModified { get; set; }
    }
}
