//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ERP_tbl_Customeremail
    {
        public string CustomerName { get; set; }
        public string OrganizationName { get; set; }
        public string CustomerCode { get; set; }
        public string email_address { get; set; }
        public string CCemail_Address { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Exclude_EInvoice { get; set; }
        public Nullable<bool> Exclude_SOA { get; set; }
        public string Updateuser { get; set; }
        public string SOAemail_address { get; set; }
        public string SOACCemail_Address { get; set; }
    }
}
