//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ERP_ServiceSOA
    {
        public long LogID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerNO { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<System.DateTime> CutoffDate { get; set; }
        public string CustomerType { get; set; }
        public string ParentCustomerName { get; set; }
        public string SOAStatus { get; set; }
        public string SOAGenStatus { get; set; }
        public Nullable<bool> IsSOAIssued { get; set; }
        public string SOAIssuedBy { get; set; }
        public Nullable<System.DateTime> SOAIssuedDate { get; set; }
        public string SOAFileName { get; set; }
        public string email_address { get; set; }
        public string CCemail_address { get; set; }
        public string EmailID { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
