//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ERP_SalesGroupBudget
    {
        public string Object { get; set; }
        public string ObjectNo { get; set; }
        public string ObjectName { get; set; }
        public string GLCode { get; set; }
        public string GLDesc { get; set; }
        public Nullable<double> ApprovedBudgetAmount { get; set; }
        public Nullable<double> SupplementaryBudget1Approved { get; set; }
        public Nullable<double> SupplementaryBudget2Approved { get; set; }
        public double CommitedAmount { get; set; }
        public Nullable<double> ActualAmount { get; set; }
    }
}
