//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tbl_DocumentDetails
    {
        public int DocID { get; set; }
        public string DocNo { get; set; }
        public string SequenceNo { get; set; }
        public string ItemNo { get; set; }
        public string ItemDescription { get; set; }
        public string CostObject { get; set; }
        public string CostObjectNo { get; set; }
        public string SourceObject { get; set; }
        public string SourceObjectNo { get; set; }
        public string SalesGroupNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> NetPriceLocal { get; set; }
        public string CostCenter { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string VendorCategory { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> RequiredOn { get; set; }
        public string PRNO { get; set; }
        public string Warehouse { get; set; }
    }
}
