//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WorkFlowDBEntities : DbContext
    {
        public WorkFlowDBEntities()
            : base("name=WorkFlowDBEntities")
        {
    		var adapter = (IObjectContextAdapter)this;
    		var objectContext = adapter.ObjectContext;
    		objectContext.CommandTimeout = 3 * 60; // value in seconds
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AuthExecutives> tbl_AuthExecutives { get; set; }
        public virtual DbSet<vw_Documents> vw_Documents { get; set; }
        public virtual DbSet<vw_ERP_CostCentreBudget> vw_ERP_CostCentreBudget { get; set; }
        public virtual DbSet<vw_ERP_SalesGroupBudget> vw_ERP_SalesGroupBudget { get; set; }
        public virtual DbSet<vw_ERP_UserDetails> vw_ERP_UserDetails { get; set; }
        public virtual DbSet<tbl_CostObject> tbl_CostObject { get; set; }
        public virtual DbSet<tbl_Division> tbl_Division { get; set; }
        public virtual DbSet<tbl_SupBudgetDetail> tbl_SupBudgetDetail { get; set; }
        public virtual DbSet<tbl_SupBudgetHeader> tbl_SupBudgetHeader { get; set; }
        public virtual DbSet<vw_ERP_ProjectBudget> vw_ERP_ProjectBudget { get; set; }
        public virtual DbSet<tbl_DocumentWorkFlow> tbl_DocumentWorkFlow { get; set; }
        public virtual DbSet<tbl_PurchaseOrder> tbl_PurchaseOrder { get; set; }
        public virtual DbSet<vw_tbl_DocumentDetails> vw_tbl_DocumentDetails { get; set; }
        public virtual DbSet<vw_DocumentDetails> vw_DocumentDetails { get; set; }
        public virtual DbSet<vw_tbl_DocumentBudget> vw_tbl_DocumentBudget { get; set; }
        public virtual DbSet<tbl_LeaveDetails_His> tbl_LeaveDetails_His { get; set; }
        public virtual DbSet<tbl_LeaveDetails> tbl_LeaveDetails { get; set; }
        public virtual DbSet<tbl_Documents> tbl_Documents { get; set; }
        public virtual DbSet<vw_Documents4AlternateApproval> vw_Documents4AlternateApproval { get; set; }
        public virtual DbSet<vw_Documents4Approval> vw_Documents4Approval { get; set; }
        public virtual DbSet<tbl_UserRoles> tbl_UserRoles { get; set; }
        public virtual DbSet<tbl_AuthExecutives_bk1> tbl_AuthExecutives_bk1 { get; set; }
        public virtual DbSet<tbl_RequestForQuotation> tbl_RequestForQuotation { get; set; }
        public virtual DbSet<tbl_RFQAttachments> tbl_RFQAttachments { get; set; }
        public virtual DbSet<tbl_PurchaseCategory> tbl_PurchaseCategory { get; set; }
        public virtual DbSet<tbl_ErrorsAndExceptions> tbl_ErrorsAndExceptions { get; set; }
        public virtual DbSet<tbl_DocMergeHeader> tbl_DocMergeHeader { get; set; }
        public virtual DbSet<tbl_DocMergeDetails> tbl_DocMergeDetails { get; set; }
        public virtual DbSet<vw_ERP_CostCentre> vw_ERP_CostCentre { get; set; }
        public virtual DbSet<vw_ERP_WarehouseBudget> vw_ERP_WarehouseBudget { get; set; }
        public virtual DbSet<vw_ERP_ServiceTaxInvoice> vw_ERP_ServiceTaxInvoice { get; set; }
        public virtual DbSet<vw_ERP_FujitecActiveContrItem> vw_ERP_FujitecActiveContrItem { get; set; }
        public virtual DbSet<tbl_SIRDocuments> tbl_SIRDocuments { get; set; }
        public virtual DbSet<vw_ERP_ServiceSOA> vw_ERP_ServiceSOA { get; set; }
        public virtual DbSet<vw_ERP_tbl_Customeremail> vw_ERP_tbl_Customeremail { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<temp_tbl_Customeremail> temp_tbl_Customeremail { get; set; }
        public virtual DbSet<vw_ERP_Organization> vw_ERP_Organization { get; set; }
    
        public virtual ObjectResult<ERP_ProjectBudgetSummary_Result> ERP_ProjectBudgetSummary(string dtlObjectNo)
        {
            var dtlObjectNoParameter = dtlObjectNo != null ?
                new ObjectParameter("DtlObjectNo", dtlObjectNo) :
                new ObjectParameter("DtlObjectNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ERP_ProjectBudgetSummary_Result>("ERP_ProjectBudgetSummary", dtlObjectNoParameter);
        }
    
        public virtual ObjectResult<string> SP_Get_PoPrEmails(string poNumber, Nullable<int> docId)
        {
            var poNumberParameter = poNumber != null ?
                new ObjectParameter("poNumber", poNumber) :
                new ObjectParameter("poNumber", typeof(string));
    
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("docId", docId) :
                new ObjectParameter("docId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Get_PoPrEmails", poNumberParameter, docIdParameter);
        }
    
        public virtual ObjectResult<string> SP_Get_PrEmails(string poNumber, Nullable<int> docId)
        {
            var poNumberParameter = poNumber != null ?
                new ObjectParameter("poNumber", poNumber) :
                new ObjectParameter("poNumber", typeof(string));
    
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("docId", docId) :
                new ObjectParameter("docId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Get_PrEmails", poNumberParameter, docIdParameter);
        }
    
        public virtual ObjectResult<string> SP_Get_AltApprovers(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Get_AltApprovers", userParameter);
        }
    
        public virtual ObjectResult<SP_CreateRFQ_Result> SP_CreateRFQ(string userId, string purchaseCategory, string purchaseRemarks, string status, string attachmentList)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var purchaseCategoryParameter = purchaseCategory != null ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(string));
    
            var purchaseRemarksParameter = purchaseRemarks != null ?
                new ObjectParameter("PurchaseRemarks", purchaseRemarks) :
                new ObjectParameter("PurchaseRemarks", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CreateRFQ_Result>("SP_CreateRFQ", userIdParameter, purchaseCategoryParameter, purchaseRemarksParameter, statusParameter, attachmentListParameter);
        }
    
        public virtual ObjectResult<tbl_RequestForQuotation> SP_GetQuote(string createdBy, string status, string quoteId, string type)
        {
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_RequestForQuotation>("SP_GetQuote", createdByParameter, statusParameter, quoteIdParameter, typeParameter);
        }
    
        public virtual ObjectResult<tbl_RequestForQuotation> SP_GetQuote(string createdBy, string status, string quoteId, string type, MergeOption mergeOption)
        {
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_RequestForQuotation>("SP_GetQuote", mergeOption, createdByParameter, statusParameter, quoteIdParameter, typeParameter);
        }
    
        public virtual ObjectResult<tbl_RFQAttachments> SP_GetQuoteAttachments(string createdBy, string status, string quoteId, string category)
        {
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_RFQAttachments>("SP_GetQuoteAttachments", createdByParameter, statusParameter, quoteIdParameter, categoryParameter);
        }
    
        public virtual ObjectResult<tbl_RFQAttachments> SP_GetQuoteAttachments(string createdBy, string status, string quoteId, string category, MergeOption mergeOption)
        {
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_RFQAttachments>("SP_GetQuoteAttachments", mergeOption, createdByParameter, statusParameter, quoteIdParameter, categoryParameter);
        }
    
        public virtual int SP_CancelQuote(string quoteList, string userId, string type, ObjectParameter sPResult, string remarks, string attachmentList, string deleteAttachmentList)
        {
            var quoteListParameter = quoteList != null ?
                new ObjectParameter("QuoteList", quoteList) :
                new ObjectParameter("QuoteList", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            var deleteAttachmentListParameter = deleteAttachmentList != null ?
                new ObjectParameter("DeleteAttachmentList", deleteAttachmentList) :
                new ObjectParameter("DeleteAttachmentList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CancelQuote", quoteListParameter, userIdParameter, typeParameter, sPResult, remarksParameter, attachmentListParameter, deleteAttachmentListParameter);
        }
    
        public virtual int SP_FinaliseQuote(string quoteId, string buyerRemarks, string attachmentList, string userId, ObjectParameter submitterEmail, ObjectParameter submitterName, ObjectParameter sPResult, string deleteAttachmentList, string status)
        {
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var buyerRemarksParameter = buyerRemarks != null ?
                new ObjectParameter("BuyerRemarks", buyerRemarks) :
                new ObjectParameter("BuyerRemarks", typeof(string));
    
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var deleteAttachmentListParameter = deleteAttachmentList != null ?
                new ObjectParameter("DeleteAttachmentList", deleteAttachmentList) :
                new ObjectParameter("DeleteAttachmentList", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FinaliseQuote", quoteIdParameter, buyerRemarksParameter, attachmentListParameter, userIdParameter, submitterEmail, submitterName, sPResult, deleteAttachmentListParameter, statusParameter);
        }
    
        public virtual int SP_IsPCVUser(string userId, ObjectParameter sPResult)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IsPCVUser", userIdParameter, sPResult);
        }
    
        public virtual int SP_GetQuoteEmailIds(string quoteNo, ObjectParameter sPResult, ObjectParameter submitterName, ObjectParameter submitterEmail, ObjectParameter buyerName, ObjectParameter buyerEmail, ObjectParameter updatedBy, ObjectParameter updaterEmail, ObjectParameter submitterManagerEmail, ObjectParameter buyerManagerEmail, ObjectParameter priority)
        {
            var quoteNoParameter = quoteNo != null ?
                new ObjectParameter("QuoteNo", quoteNo) :
                new ObjectParameter("QuoteNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetQuoteEmailIds", quoteNoParameter, sPResult, submitterName, submitterEmail, buyerName, buyerEmail, updatedBy, updaterEmail, submitterManagerEmail, buyerManagerEmail, priority);
        }
    
        public virtual int SP_IsQuoteSuperuser(string quoteId, string userId, ObjectParameter sPResult)
        {
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IsQuoteSuperuser", quoteIdParameter, userIdParameter, sPResult);
        }
    
        public virtual int SP_IsCurrentApproverIsVerifier(string workflowId, ObjectParameter sPResult)
        {
            var workflowIdParameter = workflowId != null ?
                new ObjectParameter("WorkflowId", workflowId) :
                new ObjectParameter("WorkflowId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IsCurrentApproverIsVerifier", workflowIdParameter, sPResult);
        }
    
        public virtual int SP_UpdateQuoteByBuyer(string quoteId, string buyerRemarks, string attachmentList, string userId, string deleteAttachmentList, ObjectParameter sPResult)
        {
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var buyerRemarksParameter = buyerRemarks != null ?
                new ObjectParameter("BuyerRemarks", buyerRemarks) :
                new ObjectParameter("BuyerRemarks", typeof(string));
    
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var deleteAttachmentListParameter = deleteAttachmentList != null ?
                new ObjectParameter("DeleteAttachmentList", deleteAttachmentList) :
                new ObjectParameter("DeleteAttachmentList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateQuoteByBuyer", quoteIdParameter, buyerRemarksParameter, attachmentListParameter, userIdParameter, deleteAttachmentListParameter, sPResult);
        }
    
        public virtual int SP_ReviseQuote(string quoteId, string userId, ObjectParameter sPResult, ObjectParameter revisionNo)
        {
            var quoteIdParameter = quoteId != null ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ReviseQuote", quoteIdParameter, userIdParameter, sPResult, revisionNo);
        }
    
        public virtual int SP_TestCustom()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TestCustom");
        }
    
        public virtual int GetRFQ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRFQ");
        }
    
        public virtual ObjectResult<SP_TestCustomNew_Result1> SP_TestCustomNew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TestCustomNew_Result1>("SP_TestCustomNew");
        }
    
        public virtual ObjectResult<vw_Documents4Approval> SP_GetDocuments(string userId, string status, string docNo, string mDRoleToView, string vendorName)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var mDRoleToViewParameter = mDRoleToView != null ?
                new ObjectParameter("MDRoleToView", mDRoleToView) :
                new ObjectParameter("MDRoleToView", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Documents4Approval>("SP_GetDocuments", userIdParameter, statusParameter, docNoParameter, mDRoleToViewParameter, vendorNameParameter);
        }
    
        public virtual ObjectResult<vw_Documents4Approval> SP_GetDocuments(string userId, string status, string docNo, string mDRoleToView, string vendorName, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var mDRoleToViewParameter = mDRoleToView != null ?
                new ObjectParameter("MDRoleToView", mDRoleToView) :
                new ObjectParameter("MDRoleToView", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Documents4Approval>("SP_GetDocuments", mergeOption, userIdParameter, statusParameter, docNoParameter, mDRoleToViewParameter, vendorNameParameter);
        }
    
        public virtual ObjectResult<vw_Documents4AlternateApproval> SP_GetAlternateDocuments(string userId, string status, string docNo, string mDRoleToView, string vendorName)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var mDRoleToViewParameter = mDRoleToView != null ?
                new ObjectParameter("MDRoleToView", mDRoleToView) :
                new ObjectParameter("MDRoleToView", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Documents4AlternateApproval>("SP_GetAlternateDocuments", userIdParameter, statusParameter, docNoParameter, mDRoleToViewParameter, vendorNameParameter);
        }
    
        public virtual ObjectResult<vw_Documents4AlternateApproval> SP_GetAlternateDocuments(string userId, string status, string docNo, string mDRoleToView, string vendorName, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var mDRoleToViewParameter = mDRoleToView != null ?
                new ObjectParameter("MDRoleToView", mDRoleToView) :
                new ObjectParameter("MDRoleToView", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_Documents4AlternateApproval>("SP_GetAlternateDocuments", mergeOption, userIdParameter, statusParameter, docNoParameter, mDRoleToViewParameter, vendorNameParameter);
        }
    
        public virtual int SP_IsPCVUser2(string userId, ObjectParameter sPResult)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IsPCVUser2", userIdParameter, sPResult);
        }
    
        public virtual int SP_Get_POEmailAllDetails(string poNumber, Nullable<long> docId, ObjectParameter status, ObjectParameter message)
        {
            var poNumberParameter = poNumber != null ?
                new ObjectParameter("poNumber", poNumber) :
                new ObjectParameter("poNumber", typeof(string));
    
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("docId", docId) :
                new ObjectParameter("docId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Get_POEmailAllDetails", poNumberParameter, docIdParameter, status, message);
        }
    
        public virtual ObjectResult<vw_tbl_DocumentDetails> SP_GetDocumentDetailsByID(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_tbl_DocumentDetails>("SP_GetDocumentDetailsByID", docIdParameter);
        }
    
        public virtual ObjectResult<vw_tbl_DocumentDetails> SP_GetDocumentDetailsByID(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_tbl_DocumentDetails>("SP_GetDocumentDetailsByID", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<vw_tbl_DocumentBudget> SP_GetDocumentBudgetByID(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_tbl_DocumentBudget>("SP_GetDocumentBudgetByID", docIdParameter);
        }
    
        public virtual ObjectResult<vw_tbl_DocumentBudget> SP_GetDocumentBudgetByID(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_tbl_DocumentBudget>("SP_GetDocumentBudgetByID", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetDocumentByID(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetDocumentByID", docIdParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetDocumentByID(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetDocumentByID", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetDetail> SP_GetSBDetails(string refNo)
        {
            var refNoParameter = refNo != null ?
                new ObjectParameter("RefNo", refNo) :
                new ObjectParameter("RefNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetDetail>("SP_GetSBDetails", refNoParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetDetail> SP_GetSBDetails(string refNo, MergeOption mergeOption)
        {
            var refNoParameter = refNo != null ?
                new ObjectParameter("RefNo", refNo) :
                new ObjectParameter("RefNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetDetail>("SP_GetSBDetails", mergeOption, refNoParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocWorkflowForDocStatus(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocWorkflowForDocStatus", docIdParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocWorkflowForDocStatus(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocWorkflowForDocStatus", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocPendingWorkflow(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocPendingWorkflow", docIdParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocPendingWorkflow(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocPendingWorkflow", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_UserDetails> SP_GetERPUserName(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_UserDetails>("SP_GetERPUserName", userIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_UserDetails> SP_GetERPUserName(string userId, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_UserDetails>("SP_GetERPUserName", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<string> SP_GetCostCentreBudget(string type, string objectNo)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var objectNoParameter = objectNo != null ?
                new ObjectParameter("ObjectNo", objectNo) :
                new ObjectParameter("ObjectNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetCostCentreBudget", typeParameter, objectNoParameter);
        }
    
        public virtual ObjectResult<string> SP_GetProjectBudget(string type, string objectNo)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var objectNoParameter = objectNo != null ?
                new ObjectParameter("ObjectNo", objectNo) :
                new ObjectParameter("ObjectNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetProjectBudget", typeParameter, objectNoParameter);
        }
    
        public virtual ObjectResult<string> SP_GetSalesGroupBudget(string type, string objectNo)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var objectNoParameter = objectNo != null ?
                new ObjectParameter("ObjectNo", objectNo) :
                new ObjectParameter("ObjectNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetSalesGroupBudget", typeParameter, objectNoParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocumentWorkflowByDocID(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocumentWorkflowByDocID", docIdParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocumentWorkflowByDocID(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocumentWorkflowByDocID", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocumentWorkflowByWorkflowID(Nullable<long> workflowID)
        {
            var workflowIDParameter = workflowID.HasValue ?
                new ObjectParameter("WorkflowID", workflowID) :
                new ObjectParameter("WorkflowID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocumentWorkflowByWorkflowID", workflowIDParameter);
        }
    
        public virtual ObjectResult<tbl_DocumentWorkFlow> SP_GetDocumentWorkflowByWorkflowID(Nullable<long> workflowID, MergeOption mergeOption)
        {
            var workflowIDParameter = workflowID.HasValue ?
                new ObjectParameter("WorkflowID", workflowID) :
                new ObjectParameter("WorkflowID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocumentWorkFlow>("SP_GetDocumentWorkflowByWorkflowID", mergeOption, workflowIDParameter);
        }
    
        public virtual ObjectResult<tbl_LeaveDetails_His> SP_GetLeaveDetailsHistory(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_LeaveDetails_His>("SP_GetLeaveDetailsHistory", userParameter);
        }
    
        public virtual ObjectResult<tbl_LeaveDetails_His> SP_GetLeaveDetailsHistory(string user, MergeOption mergeOption)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_LeaveDetails_His>("SP_GetLeaveDetailsHistory", mergeOption, userParameter);
        }
    
        public virtual ObjectResult<tbl_LeaveDetails> SP_GetLeaveDetails(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_LeaveDetails>("SP_GetLeaveDetails", userParameter);
        }
    
        public virtual ObjectResult<tbl_LeaveDetails> SP_GetLeaveDetails(string user, MergeOption mergeOption)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_LeaveDetails>("SP_GetLeaveDetails", mergeOption, userParameter);
        }
    
        public virtual ObjectResult<tbl_PurchaseOrder> SP_GetPurchaseOrder(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_PurchaseOrder>("SP_GetPurchaseOrder", docIdParameter);
        }
    
        public virtual ObjectResult<tbl_PurchaseOrder> SP_GetPurchaseOrder(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_PurchaseOrder>("SP_GetPurchaseOrder", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetHeader> SP_GetSBHeader(string refNo)
        {
            var refNoParameter = refNo != null ?
                new ObjectParameter("RefNo", refNo) :
                new ObjectParameter("RefNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetHeader>("SP_GetSBHeader", refNoParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetHeader> SP_GetSBHeader(string refNo, MergeOption mergeOption)
        {
            var refNoParameter = refNo != null ?
                new ObjectParameter("RefNo", refNo) :
                new ObjectParameter("RefNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetHeader>("SP_GetSBHeader", mergeOption, refNoParameter);
        }
    
        public virtual ObjectResult<vw_ERP_UserDetails> SP_GetUserByID(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_UserDetails>("SP_GetUserByID", userIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_UserDetails> SP_GetUserByID(string userId, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_UserDetails>("SP_GetUserByID", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<tbl_AuthExecutives> SP_GetAuthorizeExecutive(string approver)
        {
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_AuthExecutives>("SP_GetAuthorizeExecutive", approverParameter);
        }
    
        public virtual ObjectResult<tbl_AuthExecutives> SP_GetAuthorizeExecutive(string approver, MergeOption mergeOption)
        {
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_AuthExecutives>("SP_GetAuthorizeExecutive", mergeOption, approverParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetApprovedPR(string status, string docNo, string vendorName)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetApprovedPR", statusParameter, docNoParameter, vendorNameParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetApprovedPR(string status, string docNo, string vendorName, MergeOption mergeOption)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetApprovedPR", mergeOption, statusParameter, docNoParameter, vendorNameParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetSubmittedDocuments(string userId, string status, string docNo)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetSubmittedDocuments", userIdParameter, statusParameter, docNoParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetSubmittedDocuments(string userId, string status, string docNo, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetSubmittedDocuments", mergeOption, userIdParameter, statusParameter, docNoParameter);
        }
    
        public virtual ObjectResult<tbl_PurchaseOrder> SP_GetAllPurchaseOrders(Nullable<bool> status, string docNo, string buyerName, string vendorName)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var buyerNameParameter = buyerName != null ?
                new ObjectParameter("BuyerName", buyerName) :
                new ObjectParameter("BuyerName", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_PurchaseOrder>("SP_GetAllPurchaseOrders", statusParameter, docNoParameter, buyerNameParameter, vendorNameParameter);
        }
    
        public virtual ObjectResult<tbl_PurchaseOrder> SP_GetAllPurchaseOrders(Nullable<bool> status, string docNo, string buyerName, string vendorName, MergeOption mergeOption)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("DocNo", docNo) :
                new ObjectParameter("DocNo", typeof(string));
    
            var buyerNameParameter = buyerName != null ?
                new ObjectParameter("BuyerName", buyerName) :
                new ObjectParameter("BuyerName", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_PurchaseOrder>("SP_GetAllPurchaseOrders", mergeOption, statusParameter, docNoParameter, buyerNameParameter, vendorNameParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetHeader> SP_GetSupBudget(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetHeader>("SP_GetSupBudget", userIdParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetHeader> SP_GetSupBudget(string userId, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetHeader>("SP_GetSupBudget", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetHeader> SP_GetALLSBHeader(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetHeader>("SP_GetALLSBHeader", userIdParameter);
        }
    
        public virtual ObjectResult<tbl_SupBudgetHeader> SP_GetALLSBHeader(string userId, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SupBudgetHeader>("SP_GetALLSBHeader", mergeOption, userIdParameter);
        }
    
        public virtual int SP_MergePR(string docIDList, ObjectParameter result, ObjectParameter message, string userId)
        {
            var docIDListParameter = docIDList != null ?
                new ObjectParameter("DocIDList", docIDList) :
                new ObjectParameter("DocIDList", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MergePR", docIDListParameter, result, message, userIdParameter);
        }
    
        public virtual int SP_ValidateMergePR(string docIdList, ObjectParameter result, ObjectParameter message)
        {
            var docIdListParameter = docIdList != null ?
                new ObjectParameter("DocIdList", docIdList) :
                new ObjectParameter("DocIdList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ValidateMergePR", docIdListParameter, result, message);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetChildPR(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetChildPR", docIdParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_GetChildPR(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_GetChildPR", mergeOption, docIdParameter);
        }
    
        public virtual int SP_UpdateSummaryDoc(Nullable<long> docId, string status, string userId, ObjectParameter result)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateSummaryDoc", docIdParameter, statusParameter, userIdParameter, result);
        }
    
        public virtual int SP_InsertLog(string userName, string controller, string method, string message)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var controllerParameter = controller != null ?
                new ObjectParameter("Controller", controller) :
                new ObjectParameter("Controller", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("Method", method) :
                new ObjectParameter("Method", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertLog", userNameParameter, controllerParameter, methodParameter, messageParameter);
        }
    
        public virtual int SP_CheckRFQStatus(string rFQNo, ObjectParameter sPResult, ObjectParameter message)
        {
            var rFQNoParameter = rFQNo != null ?
                new ObjectParameter("RFQNo", rFQNo) :
                new ObjectParameter("RFQNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CheckRFQStatus", rFQNoParameter, sPResult, message);
        }
    
        public virtual ObjectResult<tbl_RFQAttachments> SP_GetRFQAttachmetsForSubmitDoc(string attachmentList)
        {
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_RFQAttachments>("SP_GetRFQAttachmetsForSubmitDoc", attachmentListParameter);
        }
    
        public virtual ObjectResult<tbl_RFQAttachments> SP_GetRFQAttachmetsForSubmitDoc(string attachmentList, MergeOption mergeOption)
        {
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_RFQAttachments>("SP_GetRFQAttachmetsForSubmitDoc", mergeOption, attachmentListParameter);
        }
    
        public virtual int SP_GetQuoteAttachmentCount(string rFQNo, ObjectParameter requestorCount, ObjectParameter buyerCount)
        {
            var rFQNoParameter = rFQNo != null ?
                new ObjectParameter("RFQNo", rFQNo) :
                new ObjectParameter("RFQNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetQuoteAttachmentCount", rFQNoParameter, requestorCount, buyerCount);
        }
    
        public virtual ObjectResult<tbl_DocMergeDetails> SP_GetMergeDocDetails(Nullable<long> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocMergeDetails>("SP_GetMergeDocDetails", docIdParameter);
        }
    
        public virtual ObjectResult<tbl_DocMergeDetails> SP_GetMergeDocDetails(Nullable<long> docId, MergeOption mergeOption)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_DocMergeDetails>("SP_GetMergeDocDetails", mergeOption, docIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_CostCentre> SP_GetCostCentre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_CostCentre>("SP_GetCostCentre");
        }
    
        public virtual ObjectResult<vw_ERP_CostCentre> SP_GetCostCentre(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_CostCentre>("SP_GetCostCentre", mergeOption);
        }
    
        public virtual int SP_ValidateDocument(string docIDList, ObjectParameter result, ObjectParameter message)
        {
            var docIDListParameter = docIDList != null ?
                new ObjectParameter("DocIDList", docIDList) :
                new ObjectParameter("DocIDList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ValidateDocument", docIDListParameter, result, message);
        }
    
        public virtual ObjectResult<string> SP_GetWarehouseBudget(string type, string objectNo)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var objectNoParameter = objectNo != null ?
                new ObjectParameter("ObjectNo", objectNo) :
                new ObjectParameter("ObjectNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetWarehouseBudget", typeParameter, objectNoParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceTaxInvoice> SP_EInvoice_View_GetServiceTaxInvoice(string status, string customerName, string period, string invoiceType, string organization, string lastThreeMonthsPeriodList)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            var invoiceTypeParameter = invoiceType != null ?
                new ObjectParameter("InvoiceType", invoiceType) :
                new ObjectParameter("InvoiceType", typeof(string));
    
            var organizationParameter = organization != null ?
                new ObjectParameter("Organization", organization) :
                new ObjectParameter("Organization", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceTaxInvoice>("SP_EInvoice_View_GetServiceTaxInvoice", statusParameter, customerNameParameter, periodParameter, invoiceTypeParameter, organizationParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceTaxInvoice> SP_EInvoice_View_GetServiceTaxInvoice(string status, string customerName, string period, string invoiceType, string organization, string lastThreeMonthsPeriodList, MergeOption mergeOption)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            var invoiceTypeParameter = invoiceType != null ?
                new ObjectParameter("InvoiceType", invoiceType) :
                new ObjectParameter("InvoiceType", typeof(string));
    
            var organizationParameter = organization != null ?
                new ObjectParameter("Organization", organization) :
                new ObjectParameter("Organization", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceTaxInvoice>("SP_EInvoice_View_GetServiceTaxInvoice", mergeOption, statusParameter, customerNameParameter, periodParameter, invoiceTypeParameter, organizationParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetSIRDocuments(string billToParty, string period)
        {
            var billToPartyParameter = billToParty != null ?
                new ObjectParameter("BillToParty", billToParty) :
                new ObjectParameter("BillToParty", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetSIRDocuments", billToPartyParameter, periodParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetSIRDocuments(string billToParty, string period, MergeOption mergeOption)
        {
            var billToPartyParameter = billToParty != null ?
                new ObjectParameter("BillToParty", billToParty) :
                new ObjectParameter("BillToParty", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetSIRDocuments", mergeOption, billToPartyParameter, periodParameter);
        }
    
        public virtual int SP_EInvoice_View_UpdateSIRDocumentStatus(string transID, string userId, ObjectParameter result, ObjectParameter message)
        {
            var transIDParameter = transID != null ?
                new ObjectParameter("TransID", transID) :
                new ObjectParameter("TransID", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EInvoice_View_UpdateSIRDocumentStatus", transIDParameter, userIdParameter, result, message);
        }
    
        public virtual ObjectResult<vw_ERP_FujitecActiveContrItem> SP_EInvoice_View_GetActiveContract(string billToParty)
        {
            var billToPartyParameter = billToParty != null ?
                new ObjectParameter("BillToParty", billToParty) :
                new ObjectParameter("BillToParty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_FujitecActiveContrItem>("SP_EInvoice_View_GetActiveContract", billToPartyParameter);
        }
    
        public virtual ObjectResult<vw_ERP_FujitecActiveContrItem> SP_EInvoice_View_GetActiveContract(string billToParty, MergeOption mergeOption)
        {
            var billToPartyParameter = billToParty != null ?
                new ObjectParameter("BillToParty", billToParty) :
                new ObjectParameter("BillToParty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_FujitecActiveContrItem>("SP_EInvoice_View_GetActiveContract", mergeOption, billToPartyParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceTaxInvoice> SP_EInvoice_View_GetServiceTaxInvoiceByID(string logID)
        {
            var logIDParameter = logID != null ?
                new ObjectParameter("LogID", logID) :
                new ObjectParameter("LogID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceTaxInvoice>("SP_EInvoice_View_GetServiceTaxInvoiceByID", logIDParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceTaxInvoice> SP_EInvoice_View_GetServiceTaxInvoiceByID(string logID, MergeOption mergeOption)
        {
            var logIDParameter = logID != null ?
                new ObjectParameter("LogID", logID) :
                new ObjectParameter("LogID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceTaxInvoice>("SP_EInvoice_View_GetServiceTaxInvoiceByID", mergeOption, logIDParameter);
        }
    
        public virtual int SP_EInvoice_View_GetEmailContent(string logId, ObjectParameter subject, ObjectParameter body, ObjectParameter site, ObjectParameter addressLine1, ObjectParameter billingPlanDescription)
        {
            var logIdParameter = logId != null ?
                new ObjectParameter("LogId", logId) :
                new ObjectParameter("LogId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EInvoice_View_GetEmailContent", logIdParameter, subject, body, site, addressLine1, billingPlanDescription);
        }
    
        public virtual int SP_EInvoice_View_SaveEmailDetails(string invoiceList, string to, string cC, string subject, string body, string attachmentLocation, string issuedBy, string attachmentList, ObjectParameter result, ObjectParameter message, string mailSendBy)
        {
            var invoiceListParameter = invoiceList != null ?
                new ObjectParameter("InvoiceList", invoiceList) :
                new ObjectParameter("InvoiceList", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(string));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("Subject", subject) :
                new ObjectParameter("Subject", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("Body", body) :
                new ObjectParameter("Body", typeof(string));
    
            var attachmentLocationParameter = attachmentLocation != null ?
                new ObjectParameter("AttachmentLocation", attachmentLocation) :
                new ObjectParameter("AttachmentLocation", typeof(string));
    
            var issuedByParameter = issuedBy != null ?
                new ObjectParameter("IssuedBy", issuedBy) :
                new ObjectParameter("IssuedBy", typeof(string));
    
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            var mailSendByParameter = mailSendBy != null ?
                new ObjectParameter("MailSendBy", mailSendBy) :
                new ObjectParameter("MailSendBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EInvoice_View_SaveEmailDetails", invoiceListParameter, toParameter, cCParameter, subjectParameter, bodyParameter, attachmentLocationParameter, issuedByParameter, attachmentListParameter, result, message, mailSendByParameter);
        }
    
        public virtual int SP_EInvoice_Email_UpdateIssueEInvoiceStatus(Nullable<long> notificationID, string invoiceList, string issuedBy, string status)
        {
            var notificationIDParameter = notificationID.HasValue ?
                new ObjectParameter("NotificationID", notificationID) :
                new ObjectParameter("NotificationID", typeof(long));
    
            var invoiceListParameter = invoiceList != null ?
                new ObjectParameter("InvoiceList", invoiceList) :
                new ObjectParameter("InvoiceList", typeof(string));
    
            var issuedByParameter = issuedBy != null ?
                new ObjectParameter("IssuedBy", issuedBy) :
                new ObjectParameter("IssuedBy", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EInvoice_Email_UpdateIssueEInvoiceStatus", notificationIDParameter, invoiceListParameter, issuedByParameter, statusParameter);
        }
    
        public virtual int SP_EInvoice_View_GetLastSIRConsolidatedOn(ObjectParameter lastConsolidated)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EInvoice_View_GetLastSIRConsolidatedOn", lastConsolidated);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetSIRListForDashboard(string status, string customerName, string period, string sIRStatus, string site, string salesGroup, string lastThreeMonthsPeriodList)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            var sIRStatusParameter = sIRStatus != null ?
                new ObjectParameter("SIRStatus", sIRStatus) :
                new ObjectParameter("SIRStatus", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var salesGroupParameter = salesGroup != null ?
                new ObjectParameter("SalesGroup", salesGroup) :
                new ObjectParameter("SalesGroup", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetSIRListForDashboard", statusParameter, customerNameParameter, periodParameter, sIRStatusParameter, siteParameter, salesGroupParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetSIRListForDashboard(string status, string customerName, string period, string sIRStatus, string site, string salesGroup, string lastThreeMonthsPeriodList, MergeOption mergeOption)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            var sIRStatusParameter = sIRStatus != null ?
                new ObjectParameter("SIRStatus", sIRStatus) :
                new ObjectParameter("SIRStatus", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var salesGroupParameter = salesGroup != null ?
                new ObjectParameter("SalesGroup", salesGroup) :
                new ObjectParameter("SalesGroup", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetSIRListForDashboard", mergeOption, statusParameter, customerNameParameter, periodParameter, sIRStatusParameter, siteParameter, salesGroupParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetSIRDocumentByID(Nullable<long> transId)
        {
            var transIdParameter = transId.HasValue ?
                new ObjectParameter("TransId", transId) :
                new ObjectParameter("TransId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetSIRDocumentByID", transIdParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetSIRDocumentByID(Nullable<long> transId, MergeOption mergeOption)
        {
            var transIdParameter = transId.HasValue ?
                new ObjectParameter("TransId", transId) :
                new ObjectParameter("TransId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetSIRDocumentByID", mergeOption, transIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceTaxInvoice> SP_EInvoice_View_GetAllServiceTaxInvoiceByStatus(string status, string lastThreeMonthsPeriodList)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceTaxInvoice>("SP_EInvoice_View_GetAllServiceTaxInvoiceByStatus", statusParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceTaxInvoice> SP_EInvoice_View_GetAllServiceTaxInvoiceByStatus(string status, string lastThreeMonthsPeriodList, MergeOption mergeOption)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceTaxInvoice>("SP_EInvoice_View_GetAllServiceTaxInvoiceByStatus", mergeOption, statusParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetAllSIRList(string status, string lastThreeMonthsPeriodList)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetAllSIRList", statusParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_GetAllSIRList(string status, string lastThreeMonthsPeriodList, MergeOption mergeOption)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var lastThreeMonthsPeriodListParameter = lastThreeMonthsPeriodList != null ?
                new ObjectParameter("LastThreeMonthsPeriodList", lastThreeMonthsPeriodList) :
                new ObjectParameter("LastThreeMonthsPeriodList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_GetAllSIRList", mergeOption, statusParameter, lastThreeMonthsPeriodListParameter);
        }
    
        public virtual int SP_EInvoice_View_IsServiceAdminUser(string userId, ObjectParameter sPResult)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EInvoice_View_IsServiceAdminUser", userIdParameter, sPResult);
        }
    
        public virtual ObjectResult<vw_ERP_UserDetails> SP_GetAllERPUsers(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_UserDetails>("SP_GetAllERPUsers", userIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_UserDetails> SP_GetAllERPUsers(string userId, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_UserDetails>("SP_GetAllERPUsers", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<tbl_UserRoles> SP_GetUserRoleByID(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_UserRoles>("SP_GetUserRoleByID", userIdParameter);
        }
    
        public virtual ObjectResult<tbl_UserRoles> SP_GetUserRoleByID(string userId, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_UserRoles>("SP_GetUserRoleByID", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceSOA> SP_SOA_View_GetALLSOAList(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceSOA>("SP_SOA_View_GetALLSOAList", statusParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceSOA> SP_SOA_View_GetALLSOAList(string status, MergeOption mergeOption)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceSOA>("SP_SOA_View_GetALLSOAList", mergeOption, statusParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceSOA> SP_SOA_View_GetSOAListForFDashboard(string customerName, string organizationName, string customerType, string parentOrganizationName, string status, string period)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var organizationNameParameter = organizationName != null ?
                new ObjectParameter("OrganizationName", organizationName) :
                new ObjectParameter("OrganizationName", typeof(string));
    
            var customerTypeParameter = customerType != null ?
                new ObjectParameter("CustomerType", customerType) :
                new ObjectParameter("CustomerType", typeof(string));
    
            var parentOrganizationNameParameter = parentOrganizationName != null ?
                new ObjectParameter("ParentOrganizationName", parentOrganizationName) :
                new ObjectParameter("ParentOrganizationName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceSOA>("SP_SOA_View_GetSOAListForFDashboard", customerNameParameter, organizationNameParameter, customerTypeParameter, parentOrganizationNameParameter, statusParameter, periodParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceSOA> SP_SOA_View_GetSOAListForFDashboard(string customerName, string organizationName, string customerType, string parentOrganizationName, string status, string period, MergeOption mergeOption)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var organizationNameParameter = organizationName != null ?
                new ObjectParameter("OrganizationName", organizationName) :
                new ObjectParameter("OrganizationName", typeof(string));
    
            var customerTypeParameter = customerType != null ?
                new ObjectParameter("CustomerType", customerType) :
                new ObjectParameter("CustomerType", typeof(string));
    
            var parentOrganizationNameParameter = parentOrganizationName != null ?
                new ObjectParameter("ParentOrganizationName", parentOrganizationName) :
                new ObjectParameter("ParentOrganizationName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceSOA>("SP_SOA_View_GetSOAListForFDashboard", mergeOption, customerNameParameter, organizationNameParameter, customerTypeParameter, parentOrganizationNameParameter, statusParameter, periodParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceSOA> SP_SOA_View_GetSOAByID(Nullable<long> logID)
        {
            var logIDParameter = logID.HasValue ?
                new ObjectParameter("LogID", logID) :
                new ObjectParameter("LogID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceSOA>("SP_SOA_View_GetSOAByID", logIDParameter);
        }
    
        public virtual ObjectResult<vw_ERP_ServiceSOA> SP_SOA_View_GetSOAByID(Nullable<long> logID, MergeOption mergeOption)
        {
            var logIDParameter = logID.HasValue ?
                new ObjectParameter("LogID", logID) :
                new ObjectParameter("LogID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_ServiceSOA>("SP_SOA_View_GetSOAByID", mergeOption, logIDParameter);
        }
    
        public virtual int SP_SOA_View_UpdateAsException(string idList, string userId)
        {
            var idListParameter = idList != null ?
                new ObjectParameter("IdList", idList) :
                new ObjectParameter("IdList", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SOA_View_UpdateAsException", idListParameter, userIdParameter);
        }
    
        public virtual int SP_CreateQuote(string userId, string purchaseCategory, string purchaseRemarks, string status, string attachmentList, string quoteNo, string deleteAttachmentList, ObjectParameter sPResult, ObjectParameter buyerName, ObjectParameter buyerEmail, ObjectParameter retQuoteNo, Nullable<System.DateTime> requiredDate, string type, Nullable<int> priority, ObjectParameter isResubmitted)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var purchaseCategoryParameter = purchaseCategory != null ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(string));
    
            var purchaseRemarksParameter = purchaseRemarks != null ?
                new ObjectParameter("PurchaseRemarks", purchaseRemarks) :
                new ObjectParameter("PurchaseRemarks", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var attachmentListParameter = attachmentList != null ?
                new ObjectParameter("AttachmentList", attachmentList) :
                new ObjectParameter("AttachmentList", typeof(string));
    
            var quoteNoParameter = quoteNo != null ?
                new ObjectParameter("QuoteNo", quoteNo) :
                new ObjectParameter("QuoteNo", typeof(string));
    
            var deleteAttachmentListParameter = deleteAttachmentList != null ?
                new ObjectParameter("DeleteAttachmentList", deleteAttachmentList) :
                new ObjectParameter("DeleteAttachmentList", typeof(string));
    
            var requiredDateParameter = requiredDate.HasValue ?
                new ObjectParameter("RequiredDate", requiredDate) :
                new ObjectParameter("RequiredDate", typeof(System.DateTime));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var priorityParameter = priority.HasValue ?
                new ObjectParameter("Priority", priority) :
                new ObjectParameter("Priority", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateQuote", userIdParameter, purchaseCategoryParameter, purchaseRemarksParameter, statusParameter, attachmentListParameter, quoteNoParameter, deleteAttachmentListParameter, sPResult, buyerName, buyerEmail, retQuoteNo, requiredDateParameter, typeParameter, priorityParameter, isResubmitted);
        }
    
        public virtual int SP_SOA_View_UpdateSOAStatusToJobQueue(Nullable<long> logId, string toAddress, string cCAddress, string userId)
        {
            var logIdParameter = logId.HasValue ?
                new ObjectParameter("LogId", logId) :
                new ObjectParameter("LogId", typeof(long));
    
            var toAddressParameter = toAddress != null ?
                new ObjectParameter("ToAddress", toAddress) :
                new ObjectParameter("ToAddress", typeof(string));
    
            var cCAddressParameter = cCAddress != null ?
                new ObjectParameter("CCAddress", cCAddress) :
                new ObjectParameter("CCAddress", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SOA_View_UpdateSOAStatusToJobQueue", logIdParameter, toAddressParameter, cCAddressParameter, userIdParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_ExportSIRReport(string period)
        {
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_ExportSIRReport", periodParameter);
        }
    
        public virtual ObjectResult<tbl_SIRDocuments> SP_EInvoice_View_ExportSIRReport(string period, MergeOption mergeOption)
        {
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_SIRDocuments>("SP_EInvoice_View_ExportSIRReport", mergeOption, periodParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_ViewDocuments(string userId, string searchText)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_ViewDocuments", userIdParameter, searchTextParameter);
        }
    
        public virtual ObjectResult<tbl_Documents> SP_ViewDocuments(string userId, string searchText, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_Documents>("SP_ViewDocuments", mergeOption, userIdParameter, searchTextParameter);
        }
    
        public virtual ObjectResult<vw_ERP_tbl_Customeremail> SP_EInvoice_View_GetCustomerEmailDetails(string customerNo)
        {
            var customerNoParameter = customerNo != null ?
                new ObjectParameter("CustomerNo", customerNo) :
                new ObjectParameter("CustomerNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_tbl_Customeremail>("SP_EInvoice_View_GetCustomerEmailDetails", customerNoParameter);
        }
    
        public virtual ObjectResult<vw_ERP_tbl_Customeremail> SP_EInvoice_View_GetCustomerEmailDetails(string customerNo, MergeOption mergeOption)
        {
            var customerNoParameter = customerNo != null ?
                new ObjectParameter("CustomerNo", customerNo) :
                new ObjectParameter("CustomerNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_tbl_Customeremail>("SP_EInvoice_View_GetCustomerEmailDetails", mergeOption, customerNoParameter);
        }
    
        public virtual ObjectResult<tbl_User> SP_GetUserByUserID(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_User>("SP_GetUserByUserID", userIdParameter);
        }
    
        public virtual ObjectResult<tbl_User> SP_GetUserByUserID(string userId, MergeOption mergeOption)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_User>("SP_GetUserByUserID", mergeOption, userIdParameter);
        }
    
        public virtual ObjectResult<vw_ERP_tbl_Customeremail> SP_GetCustomerMaster(string customerName, string organization)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var organizationParameter = organization != null ?
                new ObjectParameter("Organization", organization) :
                new ObjectParameter("Organization", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_tbl_Customeremail>("SP_GetCustomerMaster", customerNameParameter, organizationParameter);
        }
    
        public virtual ObjectResult<vw_ERP_tbl_Customeremail> SP_GetCustomerMaster(string customerName, string organization, MergeOption mergeOption)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var organizationParameter = organization != null ?
                new ObjectParameter("Organization", organization) :
                new ObjectParameter("Organization", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_tbl_Customeremail>("SP_GetCustomerMaster", mergeOption, customerNameParameter, organizationParameter);
        }
    
        public virtual int SP_CheckCustomerCodeExists(string customerCode, ObjectParameter result, ObjectParameter message)
        {
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CheckCustomerCodeExists", customerCodeParameter, result, message);
        }
    
        public virtual int SP_UpdateCustomerEmail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateCustomerEmail");
        }
    
        public virtual int SP_DeleteCustomerEmail(string idList, string userId)
        {
            var idListParameter = idList != null ?
                new ObjectParameter("IdList", idList) :
                new ObjectParameter("IdList", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteCustomerEmail", idListParameter, userIdParameter);
        }
    
        public virtual int SP_AddCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AddCustomer");
        }
    
        public virtual ObjectResult<vw_ERP_tbl_Customeremail> SP_GetCustomerOrganization()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_tbl_Customeremail>("SP_GetCustomerOrganization");
        }
    
        public virtual ObjectResult<vw_ERP_tbl_Customeremail> SP_GetCustomerOrganization(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_ERP_tbl_Customeremail>("SP_GetCustomerOrganization", mergeOption);
        }
    }
}
